### ISSUE TITLE
Social media icons are too large in the footer section

### ISSUE THREAD

**Issue by V8V88V8V88** [thefossclub/thefossclub.github.io#3]
social media icons in the footer section are disproportionately large compared to other elements on the page (e.g., text, links). This makes the footer look unbalanced and may affect the overall design aesthetics, especially on smaller screens.

**Steps to Reproduce:**

1. Navigate to the website's footer.
2. Observe the size of the social media icons relative to the surrounding elements (text and links).

![Screenshot From 2024-10-01 17-22-47](https://github.com/user-attachments/assets/4ce05325-44d0-4b34-939e-7036ea8ce077)

**Comment by harish08102004** [comment]
Hey @V8V88V8V88 I can work on this.

**Comment by shivam8112005** [comment]
i would like to contribute to this issue

**Comment by V8V88V8V88** [comment]
sure go ahead @harish08102004 @shivam8112005 , it's a small issue anyway you should be able to resolve it without an issue.
