### ISSUE TITLE
Implement a better light theme and a unified UI throughout the website

### ISSUE THREAD

**Issue by V8V88V8V88** [thefossclub/thefossclub.github.io#5]
![image](https://github.com/user-attachments/assets/7b9f7971-c174-4b58-b1d1-7a88d600b961)

**Problem:** The current light theme is too bright and lacks proper contrast, making it uncomfortable to read and navigate. Colors feel harsh and don't balance well, especially across different pages.

**Goal:** Improve the overall light theme with better contrast and more pleasant colors. Also, create a unified UI across the site—consistent buttons, typography, and layout elements for a cohesive experience.

**Comment by Jaiveer2525** [comment]
Suggestion / Seeking clarification :

Sounds like two distict improvement suggestions, those being 

a. Overhaul of the light theme colour pallette 

b. Unified design language.

While both are UI/UX improvements, I believe it would be profitable to spilt them into 2 issues.

**Comment by V8V88V8V88** [comment]
Hi @Jaiveer2525 Thanks for the suggestion! Both are part of the same UX overhaul, so addressing them together ensures consistency. Splitting them might add unnecessary complexity, especially since we're planning to retire this site in favor of the new one at [thefossclub.vercel.app](https://thefossclub.vercel.app/).

**Comment by IamHV856156** [comment]
you can check i have done something you like @V8V88V8V88  and @Jaiveer2525

**Comment by V8V88V8V88** [comment]
please add the references of your PR @IamHV856156

**Comment by IamHV856156** [comment]
2 min

**Comment by IamHV856156** [comment]
@V8V88V8V88 did you checked it??

**Comment by V8V88V8V88** [comment]
#12 fixed the issue, closing this
