### ISSUE TITLE
Redirect the Join button to the external registration form

### ISSUE THREAD

**Issue by V8V88V8V88** [thefossclub/thefossclub.github.io#6]
Currently, the **Join button** on the website leads to a basic form. We need to **update** this behavior so that the button **redirects directly** to the external registration form at [https://opnform.com/forms/the-foss-club-registration-nst4zs](https://opnform.com/forms/the-foss-club-registration-nst4zs). 

Please remove this existing form and ensure the button performs this redirect smoothly for a better user experience.

![image](https://github.com/user-attachments/assets/c705c172-1946-471a-a070-ed1110f3d7c2)

**Comment by Aaryan9084** [comment]
@V8V88V8V88 sir I can Do This

**Comment by V8V88V8V88** [comment]
Sure Go ahead @Aaryan9084

**Comment by Aaryan9084** [comment]
@V8V88V8V88 Done sir can you please check

**Comment by V8V88V8V88** [comment]
@Aaryan9084 you need to fix the behavior of clicking the button on "Join Now" button as the current implementation is not working. Thank you

**Comment by Jaiveer2525** [comment]
Pull Request created. 👍

**Comment by V8V88V8V88** [comment]
#9 great work. @Jaiveer2525 @Aaryan9084
